### ISSUE TITLE
Is there a way to add this repository as a source in file manager? 

### ISSUE THREAD

**Issue by ntilikp** [abratchik/kodi.repository#2]
I'd very much like to use your Advanced Settings script, but Kodi on Xbox One does not allow users to download add-ons from a .zip file unless it is through an http directory in file manager.  Is there anyway I can do that?  Thanks in advance.

**Comment by abratchik** [comment]
Hi @ntilikp I guess you may use https://abratchik.github.io/kodi.repository/matrix/ or https://abratchik.github.io/kodi.repository/leia ?

**Comment by ntilikp** [comment]
Thanks for the quick reply @abratchik.  Unfortunately those links return a 404 File Not Found page for me.  I tried adding them as a source in Kodi just in case but it couldn't retrieve directory information.

**Comment by abratchik** [comment]
and they should return 404 since there is no HTTP resource linked to this address. You need to add the file name you want to download. For example:
https://abratchik.github.io/kodi.repository/matrix/repository.abratchik/repository.abratchik-1.0.2.zip
https://abratchik.github.io/kodi.repository/leia/repository.abratchik/repository.abratchik-1.0.2.zip

etc

**Comment by SerpentDrago** [comment]
@abratchik you need to make a github pages , like this > https://github.com/jurialmunkey/jurialmunkey.github.io    which makes this https://jurialmunkey.github.io/ and put your repo zip on it . this will allow users to install the repo zip from within kodi using a kodi file source . you can not add a kodi file source as a direct link , it needs to be a html page hosting the link to the zip . just how kodi works.

If you do how Jurial has done , using your githubname.github.io as the github repo name , and then turn on github pages in the settings , it will make a short url like he has , i'm sure you can figure out the rest :) 

This will make it far easier for users to install your repo / addons . Thanks 

some users for example on xbox have no other way to get files .

**Comment by abratchik** [comment]
Hi @SerpentDrago, thanks for the advice!

I have created index.html files in the respective repositories:

Leia: https://abratchik.github.io/kodi.repository/leia/repository.abratchik/
Matrix: https://abratchik.github.io/kodi.repository/matrix/repository.abratchik/

 Was able to add these folders as the file source - works fine. Please check and let know if any issue

**Comment by abratchik** [comment]
Updated all the indexes so now the repository can be added from the link  https://abratchik.github.io/kodi.repository/ for both matrix and leya. Issue is fixed.
